# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: super-erp
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NjhiMjQwZTljOGU0MzUxMTcyZWY2NWQ5YTZjYzcxODE5ZTE1YTU4NWQzMDZlOTAwN2ExNGI4NGYwNDlhZjIyYjFkMDY5ODA5NmY4NjA3MmUxMjQ5Y2Q1OTRjMDQ2YmVmNmVlZWZmYTM4YjYxZWE1YTk3YjE3ZTBhZTY4NTBjYmE=
