package com.github.robsonrjunior.domain;

import static com.github.robsonrjunior.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProductAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductAllPropertiesEquals(Product expected, Product actual) {
        assertProductAutoGeneratedPropertiesEquals(expected, actual);
        assertProductAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductAllUpdatablePropertiesEquals(Product expected, Product actual) {
        assertProductUpdatableFieldsEquals(expected, actual);
        assertProductUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductAutoGeneratedPropertiesEquals(Product expected, Product actual) {
        assertThat(actual)
            .as("Verify Product auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductUpdatableFieldsEquals(Product expected, Product actual) {
        assertThat(actual)
            .as("Verify Product relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSku()).as("check sku").isEqualTo(expected.getSku()))
            .satisfies(a -> assertThat(a.getUnitOfMeasure()).as("check unitOfMeasure").isEqualTo(expected.getUnitOfMeasure()))
            .satisfies(a -> assertThat(a.getUnitDecimalPlaces()).as("check unitDecimalPlaces").isEqualTo(expected.getUnitDecimalPlaces()))
            .satisfies(a ->
                assertThat(a.getSalePrice()).as("check salePrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSalePrice())
            )
            .satisfies(a ->
                assertThat(a.getCostPrice()).as("check costPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCostPrice())
            )
            .satisfies(a ->
                assertThat(a.getMinStock()).as("check minStock").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMinStock())
            )
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductUpdatableRelationshipsEquals(Product expected, Product actual) {
        assertThat(actual)
            .as("Verify Product relationships")
            .satisfies(a -> assertThat(a.getSaleItems()).as("check saleItems").isEqualTo(expected.getSaleItems()))
            .satisfies(a -> assertThat(a.getStockMovements()).as("check stockMovements").isEqualTo(expected.getStockMovements()));
    }
}
