package com.github.robsonrjunior.domain;

import static com.github.robsonrjunior.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class RawMaterialAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRawMaterialAllPropertiesEquals(RawMaterial expected, RawMaterial actual) {
        assertRawMaterialAutoGeneratedPropertiesEquals(expected, actual);
        assertRawMaterialAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRawMaterialAllUpdatablePropertiesEquals(RawMaterial expected, RawMaterial actual) {
        assertRawMaterialUpdatableFieldsEquals(expected, actual);
        assertRawMaterialUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRawMaterialAutoGeneratedPropertiesEquals(RawMaterial expected, RawMaterial actual) {
        assertThat(actual)
            .as("Verify RawMaterial auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRawMaterialUpdatableFieldsEquals(RawMaterial expected, RawMaterial actual) {
        assertThat(actual)
            .as("Verify RawMaterial relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSku()).as("check sku").isEqualTo(expected.getSku()))
            .satisfies(a -> assertThat(a.getUnitOfMeasure()).as("check unitOfMeasure").isEqualTo(expected.getUnitOfMeasure()))
            .satisfies(a -> assertThat(a.getUnitDecimalPlaces()).as("check unitDecimalPlaces").isEqualTo(expected.getUnitDecimalPlaces()))
            .satisfies(a ->
                assertThat(a.getUnitCost()).as("check unitCost").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitCost())
            )
            .satisfies(a ->
                assertThat(a.getMinStock()).as("check minStock").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMinStock())
            )
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRawMaterialUpdatableRelationshipsEquals(RawMaterial expected, RawMaterial actual) {
        assertThat(actual)
            .as("Verify RawMaterial relationships")
            .satisfies(a -> assertThat(a.getStockMovements()).as("check stockMovements").isEqualTo(expected.getStockMovements()));
    }
}
