package com.github.robsonrjunior.domain;

import static com.github.robsonrjunior.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class StockMovementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockMovementAllPropertiesEquals(StockMovement expected, StockMovement actual) {
        assertStockMovementAutoGeneratedPropertiesEquals(expected, actual);
        assertStockMovementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockMovementAllUpdatablePropertiesEquals(StockMovement expected, StockMovement actual) {
        assertStockMovementUpdatableFieldsEquals(expected, actual);
        assertStockMovementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockMovementAutoGeneratedPropertiesEquals(StockMovement expected, StockMovement actual) {
        assertThat(actual)
            .as("Verify StockMovement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockMovementUpdatableFieldsEquals(StockMovement expected, StockMovement actual) {
        assertThat(actual)
            .as("Verify StockMovement relevant properties")
            .satisfies(a -> assertThat(a.getMovementDate()).as("check movementDate").isEqualTo(expected.getMovementDate()))
            .satisfies(a -> assertThat(a.getMovementType()).as("check movementType").isEqualTo(expected.getMovementType()))
            .satisfies(a ->
                assertThat(a.getQuantity()).as("check quantity").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQuantity())
            )
            .satisfies(a ->
                assertThat(a.getUnitCost()).as("check unitCost").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitCost())
            )
            .satisfies(a -> assertThat(a.getReferenceNumber()).as("check referenceNumber").isEqualTo(expected.getReferenceNumber()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockMovementUpdatableRelationshipsEquals(StockMovement expected, StockMovement actual) {
        // empty method
    }
}
