package com.github.robsonrjunior.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TenantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantAllPropertiesEquals(Tenant expected, Tenant actual) {
        assertTenantAutoGeneratedPropertiesEquals(expected, actual);
        assertTenantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantAllUpdatablePropertiesEquals(Tenant expected, Tenant actual) {
        assertTenantUpdatableFieldsEquals(expected, actual);
        assertTenantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantAutoGeneratedPropertiesEquals(Tenant expected, Tenant actual) {
        assertThat(actual)
            .as("Verify Tenant auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantUpdatableFieldsEquals(Tenant expected, Tenant actual) {
        assertThat(actual)
            .as("Verify Tenant relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantUpdatableRelationshipsEquals(Tenant expected, Tenant actual) {
        assertThat(actual)
            .as("Verify Tenant relationships")
            .satisfies(a -> assertThat(a.getCustomers()).as("check customers").isEqualTo(expected.getCustomers()))
            .satisfies(a -> assertThat(a.getSuppliers()).as("check suppliers").isEqualTo(expected.getSuppliers()))
            .satisfies(a -> assertThat(a.getPeople()).as("check people").isEqualTo(expected.getPeople()))
            .satisfies(a -> assertThat(a.getCompanies()).as("check companies").isEqualTo(expected.getCompanies()))
            .satisfies(a -> assertThat(a.getProducts()).as("check products").isEqualTo(expected.getProducts()))
            .satisfies(a -> assertThat(a.getRawMaterials()).as("check rawMaterials").isEqualTo(expected.getRawMaterials()))
            .satisfies(a -> assertThat(a.getWarehouses()).as("check warehouses").isEqualTo(expected.getWarehouses()))
            .satisfies(a -> assertThat(a.getSales()).as("check sales").isEqualTo(expected.getSales()))
            .satisfies(a -> assertThat(a.getSaleItems()).as("check saleItems").isEqualTo(expected.getSaleItems()))
            .satisfies(a -> assertThat(a.getStockMovements()).as("check stockMovements").isEqualTo(expected.getStockMovements()));
    }
}
