package com.github.robsonrjunior.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WarehouseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseAllPropertiesEquals(Warehouse expected, Warehouse actual) {
        assertWarehouseAutoGeneratedPropertiesEquals(expected, actual);
        assertWarehouseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseAllUpdatablePropertiesEquals(Warehouse expected, Warehouse actual) {
        assertWarehouseUpdatableFieldsEquals(expected, actual);
        assertWarehouseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseAutoGeneratedPropertiesEquals(Warehouse expected, Warehouse actual) {
        assertThat(actual)
            .as("Verify Warehouse auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseUpdatableFieldsEquals(Warehouse expected, Warehouse actual) {
        assertThat(actual)
            .as("Verify Warehouse relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseUpdatableRelationshipsEquals(Warehouse expected, Warehouse actual) {
        assertThat(actual)
            .as("Verify Warehouse relationships")
            .satisfies(a -> assertThat(a.getStockMovements()).as("check stockMovements").isEqualTo(expected.getStockMovements()))
            .satisfies(a -> assertThat(a.getSales()).as("check sales").isEqualTo(expected.getSales()));
    }
}
